# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mpls_lsp.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mpls_lsp.proto',
  package='mplspce',
  serialized_pb='\n\x0empls_lsp.proto\x12\x07mplspce\"\x80\x04\n\x03LSP\x12\x0e\n\x06pcc_ip\x18\x01 \x01(\t\x12\'\n\x07lsp_obj\x18\x02 \x01(\x0b\x32\x16.mplspce.LSP.LSPObject\x12\x31\n\x08lspa_obj\x18\x03 \x01(\x0b\x32\x1f.mplspce.LSP.LSPAttributeObject\x12&\n\x03\x65ro\x18\x04 \x03(\x0b\x32\x19.mplspce.LSP.EROSubObject\x12&\n\x03rro\x18\x05 \x03(\x0b\x32\x19.mplspce.LSP.RROSubObject\x12\x11\n\tbandwidth\x18\x06 \x01(\r\x1a\\\n\tLSPObject\x12\x0f\n\x07plsp_id\x18\x01 \x01(\r\x12\x11\n\tdelegated\x18\x02 \x01(\x08\x12\x16\n\x0e\x61\x64ministrative\x18\x03 \x01(\x08\x12\x13\n\x0boperational\x18\x04 \x01(\r\x1aU\n\x12LSPAttributeObject\x12\x12\n\nsetup_prio\x18\x01 \x01(\r\x12\x11\n\thold_prio\x18\x02 \x01(\r\x12\x18\n\x10local_protection\x18\x03 \x01(\x08\x1a\x41\n\x0c\x45ROSubObject\x12\r\n\x05loose\x18\x01 \x01(\x08\x12\x0f\n\x07node_ip\x18\x02 \x01(\t\x12\x11\n\tnode_mask\x18\x03 \x01(\r\x1a\x32\n\x0cRROSubObject\x12\x0f\n\x07node_ip\x18\x01 \x01(\t\x12\x11\n\tnode_mask\x18\x02 \x01(\r')




_LSP_LSPOBJECT = _descriptor.Descriptor(
  name='LSPObject',
  full_name='mplspce.LSP.LSPObject',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='plsp_id', full_name='mplspce.LSP.LSPObject.plsp_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='delegated', full_name='mplspce.LSP.LSPObject.delegated', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='administrative', full_name='mplspce.LSP.LSPObject.administrative', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='operational', full_name='mplspce.LSP.LSPObject.operational', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=242,
  serialized_end=334,
)

_LSP_LSPATTRIBUTEOBJECT = _descriptor.Descriptor(
  name='LSPAttributeObject',
  full_name='mplspce.LSP.LSPAttributeObject',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='setup_prio', full_name='mplspce.LSP.LSPAttributeObject.setup_prio', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hold_prio', full_name='mplspce.LSP.LSPAttributeObject.hold_prio', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='local_protection', full_name='mplspce.LSP.LSPAttributeObject.local_protection', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=336,
  serialized_end=421,
)

_LSP_EROSUBOBJECT = _descriptor.Descriptor(
  name='EROSubObject',
  full_name='mplspce.LSP.EROSubObject',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='loose', full_name='mplspce.LSP.EROSubObject.loose', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='node_ip', full_name='mplspce.LSP.EROSubObject.node_ip', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='node_mask', full_name='mplspce.LSP.EROSubObject.node_mask', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=423,
  serialized_end=488,
)

_LSP_RROSUBOBJECT = _descriptor.Descriptor(
  name='RROSubObject',
  full_name='mplspce.LSP.RROSubObject',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='node_ip', full_name='mplspce.LSP.RROSubObject.node_ip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='node_mask', full_name='mplspce.LSP.RROSubObject.node_mask', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=490,
  serialized_end=540,
)

_LSP = _descriptor.Descriptor(
  name='LSP',
  full_name='mplspce.LSP',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pcc_ip', full_name='mplspce.LSP.pcc_ip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lsp_obj', full_name='mplspce.LSP.lsp_obj', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lspa_obj', full_name='mplspce.LSP.lspa_obj', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ero', full_name='mplspce.LSP.ero', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rro', full_name='mplspce.LSP.rro', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bandwidth', full_name='mplspce.LSP.bandwidth', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_LSP_LSPOBJECT, _LSP_LSPATTRIBUTEOBJECT, _LSP_EROSUBOBJECT, _LSP_RROSUBOBJECT, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=28,
  serialized_end=540,
)

_LSP_LSPOBJECT.containing_type = _LSP;
_LSP_LSPATTRIBUTEOBJECT.containing_type = _LSP;
_LSP_EROSUBOBJECT.containing_type = _LSP;
_LSP_RROSUBOBJECT.containing_type = _LSP;
_LSP.fields_by_name['lsp_obj'].message_type = _LSP_LSPOBJECT
_LSP.fields_by_name['lspa_obj'].message_type = _LSP_LSPATTRIBUTEOBJECT
_LSP.fields_by_name['ero'].message_type = _LSP_EROSUBOBJECT
_LSP.fields_by_name['rro'].message_type = _LSP_RROSUBOBJECT
DESCRIPTOR.message_types_by_name['LSP'] = _LSP

class LSP(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class LSPObject(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _LSP_LSPOBJECT

    # @@protoc_insertion_point(class_scope:mplspce.LSP.LSPObject)

  class LSPAttributeObject(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _LSP_LSPATTRIBUTEOBJECT

    # @@protoc_insertion_point(class_scope:mplspce.LSP.LSPAttributeObject)

  class EROSubObject(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _LSP_EROSUBOBJECT

    # @@protoc_insertion_point(class_scope:mplspce.LSP.EROSubObject)

  class RROSubObject(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _LSP_RROSUBOBJECT

    # @@protoc_insertion_point(class_scope:mplspce.LSP.RROSubObject)
  DESCRIPTOR = _LSP

  # @@protoc_insertion_point(class_scope:mplspce.LSP)


# @@protoc_insertion_point(module_scope)
